# name: Publish
# on:
#   push:
#     branches:
#       - main

# jobs:
#   test:
#     name: Test
#     runs-on: ubuntu-latest
        
#     steps:
#     - uses: actions/checkout@v4
    
#     - name: Setup Deno
#       uses: denoland/setup-deno@v2
#       with:
#         deno-version: 2.x
    
#     - name: Cache dependencies
#       run: deno cache mod.ts
    
#     - name: Run tests with coverage
#       run: deno test

#   publish:
#     name: Publish
#     needs: test
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       id-token: write

#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Deno
#         uses: denoland/setup-deno@v2
#         with:
#           deno-version: v2.x

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'
#           registry-url: 'https://registry.npmjs.org'

#       - name: Get Version
#         id: get_version
#         run: |
#           echo "VERSION=$(jq -r .version deno.json)" >> $GITHUB_OUTPUT

#       - name: Build NPM Package
#         run: deno run -A scripts/build_npm.ts ${{ steps.get_version.outputs.VERSION }}

#       - name: Publish to NPM
#         run: cd npm && npm publish --access=public
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
